name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set env vars
      run: export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
    - name: apt-get update
      run: sudo apt-get update
    - name: install sfml
      run: sudo apt-get install libsfml-dev
    - name: make all
      run: make all
